In [1]:
p = 21888242871839275222246405745257275088548364400416034343698204186575808495617

In [2]:
from tensorflow.keras.layers import Input, BatchNormalization, Dense, Flatten
from tensorflow.keras import Model
import numpy as np

In [3]:
inputs = Input(shape=(5,5,3))
out = BatchNormalization()(inputs)
out = Flatten()(out)
out = Dense(1)(out)
model = Model(inputs, out)

In [4]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 5, 5, 3)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 5, 5, 3)        │            12 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 75)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            76 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 88 (352.00 B)

 Trainable params: 82 (328.00 B)

 Non-trainable params: 6 (24.00 B)

In [5]:
X_train = np.random.rand(100,5,5,3)
X_train

array([[[[0.60384591, 0.76706998, 0.80850231],
         [0.45634106, 0.18998775, 0.34212406],
         [0.9673473 , 0.35235242, 0.16139093],
         [0.4514518 , 0.33113734, 0.03990953],
         [0.75386766, 0.70881806, 0.24837283]],

        [[0.20110148, 0.36590138, 0.81593574],
         [0.48455094, 0.92046105, 0.00140346],
         [0.45389422, 0.88912959, 0.74518631],
         [0.38341597, 0.76196896, 0.43028356],
         [0.06075796, 0.09361846, 0.85107977]],

        [[0.55710624, 0.16777536, 0.11976239],
         [0.78132667, 0.92576022, 0.98343163],
         [0.7774776 , 0.97083323, 0.97957192],
         [0.45701702, 0.59291996, 0.24702148],
         [0.91797784, 0.33409993, 0.46745264]],

        [[0.85169133, 0.38708603, 0.34616611],
         [0.17657783, 0.11355016, 0.12754369],
         [0.78479318, 0.70544173, 0.56921611],
         [0.53588168, 0.63313098, 0.28312233],
         [0.83639061, 0.05613458, 0.03641011]],

        [[0.71609491, 0.05271848, 0.73299899],
     

In [6]:
y_train = np.random.rand(100,1)
y_train

array([[8.19095985e-01],
       [4.59638382e-01],
       [7.54672658e-01],
       [1.51200390e-01],
       [4.78800256e-01],
       [8.41520844e-01],
       [2.48384407e-01],
       [2.68887463e-01],
       [5.94268325e-02],
       [1.47597931e-04],
       [3.10540143e-01],
       [2.37477328e-01],
       [4.64621534e-03],
       [8.65580081e-02],
       [9.68020129e-01],
       [3.07443048e-01],
       [1.83834250e-01],
       [5.05352261e-01],
       [6.98174841e-01],
       [6.43714232e-01],
       [6.39176137e-01],
       [8.78077983e-01],
       [2.37425062e-02],
       [9.27386748e-02],
       [6.32237403e-01],
       [7.30487914e-01],
       [4.79035662e-01],
       [5.17103050e-01],
       [3.06989897e-01],
       [7.45704705e-01],
       [4.30433284e-01],
       [8.02704068e-01],
       [8.90053066e-01],
       [5.34460824e-01],
       [6.72815231e-01],
       [2.68878619e-01],
       [9.30288083e-01],
       [4.42969318e-01],
       [3.27714444e-01],
       [4.84329571e-01],


In [7]:
model.compile("adam", "mse")
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.7256  
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 1.9723
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step - loss: 1.7441
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step - loss: 1.8540
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 747us/step - loss: 1.7174
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - loss: 1.5487
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - loss: 1.6692
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 1.5148
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - loss: 1.3181
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 1.4388


In [8]:
model.layers[1].weights

[<KerasVariable shape=(3,), dtype=float32, path=batch_normalization/gamma>,
 <KerasVariable shape=(3,), dtype=float32, path=batch_normalization/beta>,
 <KerasVariable shape=(3,), dtype=float32, path=batch_normalization/moving_mean>,
 <KerasVariable shape=(3,), dtype=float32, path=batch_normalization/moving_variance>]

In [9]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.42583122, 0.66518831, 0.45544763],
         [0.98964015, 0.64755069, 0.46357053],
         [0.26988113, 0.1488036 , 0.01966642],
         [0.22859392, 0.0172811 , 0.0622273 ],
         [0.24630139, 0.79205505, 0.96098949]],

        [[0.1869114 , 0.60629408, 0.43855849],
         [0.55321532, 0.24176446, 0.23207878],
         [0.44428208, 0.33443009, 0.67289542],
         [0.31305482, 0.38332418, 0.30089677],
         [0.4795198 , 0.82724105, 0.17635053]],

        [[0.90115444, 0.54430382, 0.83045872],
         [0.77412927, 0.75494886, 0.62754472],
         [0.04287335, 0.63631401, 0.82108627],
         [0.28490576, 0.53365788, 0.98229127],
         [0.43788597, 0.04012721, 0.87247348]],

        [[0.8473817 , 0.00342018, 0.42719685],
         [0.63196841, 0.88994495, 0.66634868],
         [0.8383848 , 0.65584435, 0.85112477],
         [0.52520182, 0.58175594, 0.82414076],
         [0.3701879 , 0.85287308, 0.71185781]],

        [[0.17488253, 0.57199013, 0.20313468],
     

In [10]:
new_model = Model(inputs, model.layers[1].output)
y = new_model.predict(X)
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


array([[[[ 0.32352948,  0.6077688 ,  0.36199367],
         [ 0.9775543 ,  0.5872687 ,  0.37135965],
         [ 0.1426256 ,  0.00757879, -0.14047357],
         [ 0.09473196, -0.1452888 , -0.09139975],
         [ 0.11527282,  0.755225  ,  0.9448968 ]],

        [[ 0.04637976,  0.5393165 ,  0.34252006],
         [ 0.4712965 ,  0.11562647,  0.10444349],
         [ 0.34493268,  0.22333105,  0.61271673],
         [ 0.19270757,  0.28016025,  0.18379244],
         [ 0.38580883,  0.7961214 ,  0.04018736]],

        [[ 0.8749099 ,  0.46726567,  0.7943914 ],
         [ 0.7275592 ,  0.71209675,  0.5604262 ],
         [-0.12070602,  0.5742084 ,  0.7835847 ],
         [ 0.16005433,  0.45489198,  0.96945834],
         [ 0.33751315, -0.11873493,  0.84283555]],

        [[ 0.81253284, -0.16139922,  0.32941982],
         [ 0.5626509 ,  0.8690017 ,  0.6051682 ],
         [ 0.80209637,  0.59690833,  0.8182199 ],
         [ 0.43880045,  0.51079595,  0.78710663],
         [ 0.2589826 ,  0.8259133 ,  0.65764

In [11]:
gamma = model.layers[1].weights[0].numpy()
beta = model.layers[1].weights[1].numpy()
moving_mean = model.layers[1].weights[2].numpy()
moving_var = model.layers[1].weights[3].numpy()
epsilon = model.layers[1].epsilon

In [12]:
a = gamma/(moving_var+epsilon)**.5
b = beta-gamma*moving_mean/(moving_var+epsilon)**.5

In [13]:
y-(gamma*(X-moving_mean)/((moving_var+epsilon)**.5)+beta)

array([[[[ 5.80517240e-09,  7.25930150e-08, -2.98457537e-08],
         [ 8.56541345e-08,  7.81473317e-08,  1.71317017e-08],
         [ 5.89111010e-09, -4.92505054e-09,  2.11156338e-08],
         [-1.79105347e-09, -1.58378599e-08,  1.43221258e-08],
         [-1.09813150e-08,  9.23258275e-08, -6.69148024e-08]],

        [[-1.44543390e-09,  8.13925268e-08, -1.61573844e-08],
         [ 1.60176437e-08, -7.97089778e-09, -7.92654534e-09],
         [-7.88321070e-09,  3.77275967e-08, -4.68007141e-08],
         [ 3.35038775e-09,  1.52393753e-08, -1.96319461e-08],
         [-9.91450733e-09,  9.66804833e-08,  1.48735822e-08]],

        [[ 6.33648625e-08,  6.39907535e-08, -5.05588529e-08],
         [ 4.40467959e-08,  6.95079078e-08, -4.06570019e-08],
         [-1.54599301e-08,  5.38772120e-08, -4.13081969e-08],
         [-6.06994216e-09,  7.09057760e-08, -5.97652687e-08],
         [ 3.13480205e-08, -1.03577788e-08, -2.45032028e-08]],

        [[ 2.00998832e-08, -5.13689175e-09,  1.56499594e-08],
  

In [14]:
y-(a*X+b)

array([[[[-1.05967100e-08,  9.48168908e-08, -5.72857582e-08],
         [ 4.38327714e-08,  9.96888471e-08, -1.07153514e-08],
         [-3.47971940e-09, -2.67895506e-09,  1.55131372e-08],
         [-9.30043764e-09, -1.86800786e-08,  6.58685331e-09],
         [-1.92890455e-08,  1.19457896e-07, -1.19688103e-07]],

        [[-7.07555017e-09,  1.01337915e-07, -4.27510544e-08],
         [-6.12738571e-09, -2.12835249e-09, -2.41732750e-08],
         [-2.51169552e-08,  4.71551698e-08, -8.51372832e-08],
         [-7.96693944e-09,  2.65585525e-08, -3.93272258e-08],
         [-2.87369540e-08,  1.25173820e-07,  1.41946074e-09]],

        [[ 2.55329018e-08,  8.15378761e-08, -9.67911038e-08],
         [ 1.19418003e-08,  9.52044201e-08, -7.67209940e-08],
         [-1.45960515e-08,  7.49840049e-08, -8.70707831e-08],
         [-1.61181611e-08,  8.80410308e-08, -1.13606027e-07],
         [ 1.44026465e-08, -1.23161318e-08, -7.28408625e-08]],

        [[-1.53077185e-08, -8.51535847e-09, -1.03743656e-08],
  

In [15]:
X_in = [[[int(X[0][i][j][k]*2**10) for k in range(3)] for j in range(5)] for i in range(5)]
a_in = [int(a[i]*2**10) for i in range(3)]
b_in = [int(b[i]*2**20) for i in range(3)]

In [16]:
def BatchNormalizationInt(nRows, nCols, nChannels, n, X_in, a_in, b_in):
    X = [[[str(X_in[i][j][k]) for k in range(nChannels)] for j in range(nCols)] for i in range(nRows)]
    A = [str(a_in[k]) for k in range(nChannels)]
    B = [str(b_in[k]) for k in range(nChannels)]
    out = [[[None for _ in range(nChannels)] for _ in range(nCols)] for _ in range(nRows)]
    for i in range(nRows):
        for j in range(nCols):
            for k in range(nChannels):
                out[i][j][k] = (X_in[i][j][k]*a_in[k] + b_in[k])
                out[i][j][k] = str(out[i][j][k] // n)
    return X, A, B, out

In [17]:
X_in, a_in, b_in, out = BatchNormalizationInt(5, 5, 3, 2**10, X_in, a_in, b_in)
out

[[['330', '622', '369'],
  ['999', '601', '379'],
  ['145', '7', '-145'],
  ['96', '-150', '-95'],
  ['117', '773', '966']],
 [['46', '551', '350'],
  ['481', '117', '106'],
  ['351', '228', '626'],
  ['196', '286', '187'],
  ['394', '814', '40']],
 [['894', '477', '812'],
  ['743', '728', '572'],
  ['-125', '587', '800'],
  ['162', '465', '991'],
  ['344', '-122', '861']],
 [['830', '-166', '336'],
  ['575', '889', '618'],
  ['820', '610', '836'],
  ['447', '522', '804'],
  ['264', '845', '671']],
 [['32', '510', '72'],
  ['379', '721', '1010'],
  ['248', '312', '102'],
  ['338', '502', '-72'],
  ['136', '624', '259']]]

In [18]:
in_json = {
    "in": X_in,
    "a": a_in,
    "b": b_in,
    "out": out
}

In [19]:
import json

In [20]:
with open("batchNormalization_input.json", "w") as f:
    json.dump(in_json, f)