In [ ]:
p = 21888242871839275222246405745257275088548364400416034343698204186575808495617

In [ ]:
from tensorflow.keras.layers import Input, BatchNormalization, Dense, Flatten
from tensorflow.keras import Model
import numpy as np

In [10]:
inputs = Input(shape=(5,5,3))
out = BatchNormalization()(inputs)
out = Flatten()(out)
out = Dense(1)(out)
model = Model(inputs, out)

In [12]:
model.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 5, 5, 3)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 5, 5, 3)        │            12 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 75)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            76 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 88 (352.00 B)

 Trainable params: 82 (328.00 B)

 Non-trainable params: 6 (24.00 B)

In [13]:
X_train = np.random.rand(100,5,5,3)
X_train

array([[[[0.42547434, 0.94555088, 0.08728145],
         [0.79711016, 0.05639756, 0.1161714 ],
         [0.06538124, 0.39583483, 0.1960645 ],
         [0.93252151, 0.09242741, 0.42413297],
         [0.66452681, 0.87383533, 0.6936922 ]],

        [[0.52788214, 0.91814848, 0.82745402],
         [0.0771809 , 0.45004127, 0.53412011],
         [0.92626074, 0.14748341, 0.75833166],
         [0.05557902, 0.52716827, 0.91687914],
         [0.73164622, 0.10849281, 0.30011612]],

        [[0.51585312, 0.07623645, 0.29371578],
         [0.2997686 , 0.04569738, 0.43718599],
         [0.32451135, 0.24520228, 0.03545287],
         [0.78654978, 0.25509061, 0.72332871],
         [0.39959002, 0.44308585, 0.58533831]],

        [[0.2397406 , 0.16026889, 0.86286081],
         [0.55402182, 0.79761959, 0.11285965],
         [0.690326  , 0.81285191, 0.00410972],
         [0.41875107, 0.66358763, 0.21176833],
         [0.16751035, 0.71293998, 0.59242945]],

        [[0.20428295, 0.04918369, 0.45501937],
     

In [14]:
y_train = np.random.rand(100,1)
y_train

array([[0.6113366 ],
       [0.10737447],
       [0.3488707 ],
       [0.71808866],
       [0.99304948],
       [0.26757407],
       [0.11587715],
       [0.32157164],
       [0.80101184],
       [0.35105186],
       [0.3008984 ],
       [0.20978757],
       [0.71390539],
       [0.33637666],
       [0.50625545],
       [0.22503267],
       [0.94630432],
       [0.66356838],
       [0.33371343],
       [0.41222139],
       [0.11345567],
       [0.38189617],
       [0.37506902],
       [0.49330511],
       [0.97512162],
       [0.79656249],
       [0.64944268],
       [0.03091189],
       [0.4399514 ],
       [0.51040101],
       [0.24072432],
       [0.67475933],
       [0.49424796],
       [0.05461922],
       [0.53595297],
       [0.58591269],
       [0.46363301],
       [0.62342251],
       [0.21431095],
       [0.25168969],
       [0.29664938],
       [0.97234594],
       [0.11855559],
       [0.60164337],
       [0.56659357],
       [0.48527488],
       [0.66190191],
       [0.476

In [15]:
model.compile("adam", "mse")
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.0004  
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 700us/step - loss: 2.0566
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - loss: 1.9381
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - loss: 1.8680
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step - loss: 1.6860
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - loss: 1.5725
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - loss: 1.7499
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step - loss: 1.4222
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 656us/step - loss: 1.4982
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - loss: 1.3317


In [ ]:
model.layers[1].weights

[<KerasVariable shape=(3,), dtype=float32, path=batch_normalization/gamma>,
 <KerasVariable shape=(3,), dtype=float32, path=batch_normalization/beta>,
 <KerasVariable shape=(3,), dtype=float32, path=batch_normalization/moving_mean>,
 <KerasVariable shape=(3,), dtype=float32, path=batch_normalization/moving_variance>]

In [16]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.83573349, 0.4571578 , 0.33504131],
         [0.03150751, 0.10461961, 0.1553164 ],
         [0.29994496, 0.36865493, 0.4578059 ],
         [0.01929765, 0.06978601, 0.37613846],
         [0.36881054, 0.65517754, 0.53612393]],

        [[0.88150878, 0.33071198, 0.26412818],
         [0.02998327, 0.41032392, 0.0572792 ],
         [0.43281189, 0.53696526, 0.96292859],
         [0.96195933, 0.94207818, 0.88670906],
         [0.52209127, 0.25313686, 0.37191266]],

        [[0.4164608 , 0.41410808, 0.68662937],
         [0.70857627, 0.31228741, 0.96664639],
         [0.08643052, 0.80867838, 0.90971538],
         [0.01490692, 0.42278997, 0.01672697],
         [0.21293124, 0.24582049, 0.15764299]],

        [[0.9337814 , 0.04065057, 0.73857111],
         [0.08246049, 0.06309577, 0.19777623],
         [0.68239526, 0.33509039, 0.76560385],
         [0.4444294 , 0.61981861, 0.22082947],
         [0.16096521, 0.92789676, 0.84813604]],

        [[0.14639315, 0.73202245, 0.01593963],
     

In [17]:
new_model = Model(inputs, model.layers[1].output)
y = new_model.predict(X)
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


array([[[[ 0.80176157,  0.36513942,  0.16627234],
         [-0.126585  , -0.04218464, -0.04187813],
         [ 0.18328188,  0.2628829 ,  0.30845353],
         [-0.14067928, -0.08243151,  0.21386945],
         [ 0.26277584,  0.5939322 ,  0.39915845]],

        [[ 0.8546017 ,  0.21904342,  0.08414346],
         [-0.12834448,  0.31102735, -0.15542102],
         [ 0.3366549 ,  0.4573493 ,  0.8934672 ],
         [ 0.9474686 ,  0.9254184 ,  0.8051926 ],
         [ 0.43971324,  0.12941279,  0.20897529]],

        [[ 0.31778026,  0.3153996 ,  0.57346797],
         [ 0.6549795 ,  0.19775562,  0.8977729 ],
         [-0.06318542,  0.77128774,  0.83183765],
         [-0.14574765,  0.3254307 , -0.20238706],
         [ 0.08283883,  0.12095942, -0.03918356]],

        [[ 0.9149417 , -0.11609472,  0.6336249 ],
         [-0.06776816, -0.09016144,  0.0072972 ],
         [ 0.6247579 ,  0.22410227,  0.6649332 ],
         [ 0.3500654 ,  0.5530784 ,  0.03399658],
         [ 0.02285261,  0.90903306,  0.76051

In [18]:
gamma = model.layers[1].weights[0].numpy()
beta = model.layers[1].weights[1].numpy()
moving_mean = model.layers[1].weights[2].numpy()
moving_var = model.layers[1].weights[3].numpy()
epsilon = model.layers[1].epsilon

In [19]:
a = gamma/(moving_var+epsilon)**.5
b = beta-gamma*moving_mean/(moving_var+epsilon)**.5

In [20]:
y-(gamma*(X-moving_mean)/((moving_var+epsilon)**.5)+beta)

array([[[[-1.52462073e-08, -1.84665042e-08,  3.01368919e-09],
         [-1.44476716e-08, -3.91963802e-09, -9.85662925e-09],
         [ 2.16847257e-09,  2.12106357e-08, -2.54743368e-08],
         [-1.78033182e-08, -7.42305648e-10, -2.14282920e-08],
         [-1.72569903e-08, -4.63192489e-08, -3.57985496e-08]],

        [[ 5.66251080e-08, -4.24746627e-11, -1.88288165e-08],
         [-4.94273500e-09, -3.54808649e-08,  2.11894646e-08],
         [ 1.31161704e-08, -4.23091984e-09, -1.43021897e-08],
         [ 3.37918156e-08, -5.22774471e-08, -7.99844420e-08],
         [-2.79159335e-09, -1.95538785e-08, -2.85529253e-08]],

        [[ 6.20566848e-09, -3.25729413e-08, -1.12195565e-07],
         [ 3.38712056e-08,  2.60960244e-08, -1.00840250e-07],
         [-7.98440471e-09, -2.25133354e-08, -5.09768838e-08],
         [-6.87091087e-09, -1.96203116e-08,  8.49444831e-09],
         [-1.89663195e-08, -2.47665907e-08,  6.47336316e-10]],

        [[-2.84494008e-08,  5.64905067e-10, -9.64413879e-08],
  

In [21]:
y-(a*X+b)

array([[[[-4.67818091e-08, -2.81569741e-08, -2.48195964e-08],
         [-1.71223865e-08, -1.49981912e-08, -2.98627932e-08],
         [-1.01395334e-08,  1.11716947e-08, -5.86540897e-08],
         [-2.00398635e-08, -1.19580125e-08, -5.10513817e-08],
         [-3.20363434e-08, -5.52300362e-08, -7.23890972e-08]],

        [[ 2.34467896e-08, -1.02308121e-08, -4.35737949e-08],
         [-7.56275040e-09, -4.53557384e-08,  5.45287648e-09],
         [-3.95996980e-09, -1.36071560e-08, -6.94803222e-08],
         [-2.27359442e-09, -6.00585923e-08, -1.31843170e-07],
         [-2.30716614e-08, -3.00476601e-08, -5.79919790e-08]],

        [[-1.02836878e-08, -4.24329151e-08, -1.55340710e-07],
         [ 6.89883639e-09,  1.58351421e-08, -1.56180295e-07],
         [-1.26301163e-08, -3.08197288e-08, -1.03837551e-07],
         [-8.94988816e-09, -2.94461013e-08, -5.47606710e-09],
         [-2.81517041e-08, -3.52891797e-08, -1.94601520e-08]],

        [[-6.35036024e-08, -1.07655196e-08, -1.41848625e-07],
  

In [22]:
X_in = [[[int(X[0][i][j][k]*2**10) for k in range(3)] for j in range(5)] for i in range(5)]
X_in_unchanged = [[[float(X[0][i][j][k]) for k in range(3)] for j in range(5)] for i in range(5)]
a_in = [int(a[i]*2**10) for i in range(3)]
a_in_unchanged = [float(a[i]) for i in range(3)]
b_in = [int(b[i]*2**20) for i in range(3)]
b_in_unchanged = [float(b[i]) for i in range(3)]

In [23]:
def BatchNormalizationInt(nRows, nCols, nChannels, n, X_in, a_in, b_in):
    X = [[[str(X_in[i][j][k]) for k in range(nChannels)] for j in range(nCols)] for i in range(nRows)]
    A = [str(a_in[k]) for k in range(nChannels)]
    B = [str(b_in[k]) for k in range(nChannels)]
    out = [[[None for _ in range(nChannels)] for _ in range(nCols)] for _ in range(nRows)]
    for i in range(nRows):
        for j in range(nCols):
            for k in range(nChannels):
                out[i][j][k] = (X_in[i][j][k]*a_in[k] + b_in[k])
                out[i][j][k] = str(out[i][j][k] // n)
    return X, A, B, out

In [24]:
X_in, a_in, b_in, out = BatchNormalizationInt(5, 5, 3, 2**10, X_in, a_in, b_in)
out

[[['820', '373', '169'],
  ['-130', '-44', '-44'],
  ['187', '268', '314'],
  ['-145', '-85', '218'],
  ['268', '607', '407']],
 [['874', '223', '85'],
  ['-133', '318', '-160'],
  ['344', '467', '913'],
  ['970', '946', '822'],
  ['449', '132', '212']],
 [['324', '322', '586'],
  ['670', '201', '917'],
  ['-66', '789', '850'],
  ['-150', '332', '-208'],
  ['84', '122', '-41']],
 [['936', '-120', '647'],
  ['-70', '-94', '6'],
  ['638', '229', '679'],
  ['358', '565', '34'],
  ['22', '930', '777']],
 [['5', '698', '-209'],
  ['837', '772', '368'],
  ['14', '-128', '775'],
  ['350', '728', '72'],
  ['346', '259', '485']]]

In [25]:
in_json = {
    "in": X_in,
    "a": a_in,
    "b": b_in,
    "out": out,
    "in_unchanged": X_in_unchanged,
    "a_unchanged": a_in_unchanged,
    "b_unchanged": b_in_unchanged,
}

In [26]:
import json

In [27]:
with open("batchNormalization_input.json", "w") as f:
    json.dump(in_json, f)